// GENERATED by catalog/generator/generate.py — DO NOT EDIT.
// Source: catalog/catalog.yaml
//
// JSON Schemas for TimePass custom components, keyed by component name.
// Adopted Basic Catalog primitives are provided by package:genui and are
// intentionally absent here.

const String catalogId = 'https://timepass.app/catalogs/core/v1';

const Map<String, Map<String, Object?>> componentSchemas = {
  'Markdown': <String, Object?>{
    'type': 'object',
    'description': 'Prose answers (letters, explanations, drafts). GFM subset: bold, italic, lists, tables, links. No raw HTML, no images.',
    'properties': <String, Object?>{
      'text': <String, Object?>{
        'oneOf': <Object?>[
          <String, Object?>{
            'type': 'string',
          },
          <String, Object?>{
            'type': 'object',
            'properties': <String, Object?>{
              'path': <String, Object?>{
                'type': 'string',
                'pattern': '^/',
              },
            },
            'required': <Object?>[
              'path',
            ],
            'additionalProperties': false,
          },
        ],
        'description': 'Markdown source.',
      },
    },
    'required': <Object?>[
      'text',
    ],
  },
  'KeyValueGrid': <String, Object?>{
    'type': 'object',
    'description': 'Labeled facts in a 1-2 column grid. The generic-tier workhorse.',
    'properties': <String, Object?>{
      'title': <String, Object?>{
        'oneOf': <Object?>[
          <String, Object?>{
            'type': 'string',
          },
          <String, Object?>{
            'type': 'object',
            'properties': <String, Object?>{
              'path': <String, Object?>{
                'type': 'string',
                'pattern': '^/',
              },
            },
            'required': <Object?>[
              'path',
            ],
            'additionalProperties': false,
          },
        ],
      },
      'columns': <String, Object?>{
        'oneOf': <Object?>[
          <String, Object?>{
            'type': 'integer',
            'enum': <Object?>[
              1,
              2,
            ],
            'default': 2,
          },
          <String, Object?>{
            'type': 'object',
            'properties': <String, Object?>{
              'path': <String, Object?>{
                'type': 'string',
                'pattern': '^/',
              },
            },
            'required': <Object?>[
              'path',
            ],
            'additionalProperties': false,
          },
        ],
      },
      'items': <String, Object?>{
        'oneOf': <Object?>[
          <String, Object?>{
            'type': 'array',
            'items': <String, Object?>{
              'type': 'object',
              'properties': <String, Object?>{
                'label': <String, Object?>{
                  'oneOf': <Object?>[
                    <String, Object?>{
                      'type': 'string',
                    },
                    <String, Object?>{
                      'type': 'object',
                      'properties': <String, Object?>{
                        'path': <String, Object?>{
                          'type': 'string',
                          'pattern': '^/',
                        },
                      },
                      'required': <Object?>[
                        'path',
                      ],
                      'additionalProperties': false,
                    },
                  ],
                },
                'value': <String, Object?>{
                  'oneOf': <Object?>[
                    <String, Object?>{
                      'type': 'string',
                    },
                    <String, Object?>{
                      'type': 'object',
                      'properties': <String, Object?>{
                        'path': <String, Object?>{
                          'type': 'string',
                          'pattern': '^/',
                        },
                      },
                      'required': <Object?>[
                        'path',
                      ],
                      'additionalProperties': false,
                    },
                  ],
                },
                'icon': <String, Object?>{
                  'oneOf': <Object?>[
                    <String, Object?>{
                      'type': 'string',
                    },
                    <String, Object?>{
                      'type': 'object',
                      'properties': <String, Object?>{
                        'path': <String, Object?>{
                          'type': 'string',
                          'pattern': '^/',
                        },
                      },
                      'required': <Object?>[
                        'path',
                      ],
                      'additionalProperties': false,
                    },
                  ],
                },
                'emphasis': <String, Object?>{
                  'oneOf': <Object?>[
                    <String, Object?>{
                      'type': 'boolean',
                      'default': false,
                    },
                    <String, Object?>{
                      'type': 'object',
                      'properties': <String, Object?>{
                        'path': <String, Object?>{
                          'type': 'string',
                          'pattern': '^/',
                        },
                      },
                      'required': <Object?>[
                        'path',
                      ],
                      'additionalProperties': false,
                    },
                  ],
                },
              },
              'additionalProperties': false,
              'required': <Object?>[
                'label',
                'value',
              ],
            },
            'minItems': 1,
            'maxItems': 12,
          },
          <String, Object?>{
            'type': 'object',
            'properties': <String, Object?>{
              'path': <String, Object?>{
                'type': 'string',
                'pattern': '^/',
              },
            },
            'required': <Object?>[
              'path',
            ],
            'additionalProperties': false,
          },
        ],
      },
    },
    'required': <Object?>[
      'items',
    ],
  },
  'Notice': <String, Object?>{
    'type': 'object',
    'description': 'Callout for info/warnings and mandatory compliance disclosures (cricket lag, astrology disclaimer).',
    'properties': <String, Object?>{
      'text': <String, Object?>{
        'oneOf': <Object?>[
          <String, Object?>{
            'type': 'string',
          },
          <String, Object?>{
            'type': 'object',
            'properties': <String, Object?>{
              'path': <String, Object?>{
                'type': 'string',
                'pattern': '^/',
              },
            },
            'required': <Object?>[
              'path',
            ],
            'additionalProperties': false,
          },
        ],
      },
      'variant': <String, Object?>{
        'oneOf': <Object?>[
          <String, Object?>{
            'type': 'string',
            'enum': <Object?>[
              'info',
              'warning',
              'legal',
              'success',
            ],
          },
          <String, Object?>{
            'type': 'object',
            'properties': <String, Object?>{
              'path': <String, Object?>{
                'type': 'string',
                'pattern': '^/',
              },
            },
            'required': <Object?>[
              'path',
            ],
            'additionalProperties': false,
          },
        ],
      },
      'icon': <String, Object?>{
        'oneOf': <Object?>[
          <String, Object?>{
            'type': 'string',
          },
          <String, Object?>{
            'type': 'object',
            'properties': <String, Object?>{
              'path': <String, Object?>{
                'type': 'string',
                'pattern': '^/',
              },
            },
            'required': <Object?>[
              'path',
            ],
            'additionalProperties': false,
          },
        ],
      },
      'dense': <String, Object?>{
        'oneOf': <Object?>[
          <String, Object?>{
            'type': 'boolean',
            'default': false,
          },
          <String, Object?>{
            'type': 'object',
            'properties': <String, Object?>{
              'path': <String, Object?>{
                'type': 'string',
                'pattern': '^/',
              },
            },
            'required': <Object?>[
              'path',
            ],
            'additionalProperties': false,
          },
        ],
      },
    },
    'required': <Object?>[
      'text',
      'variant',
    ],
  },
  'FollowUpChips': <String, Object?>{
    'type': 'object',
    'description': 'Suggested next queries; always the last child of the root Column. Tapping a chip sends its query as a new user message.',
    'properties': <String, Object?>{
      'suggestions': <String, Object?>{
        'oneOf': <Object?>[
          <String, Object?>{
            'type': 'array',
            'items': <String, Object?>{
              'type': 'object',
              'properties': <String, Object?>{
                'label': <String, Object?>{
                  'oneOf': <Object?>[
                    <String, Object?>{
                      'type': 'string',
                    },
                    <String, Object?>{
                      'type': 'object',
                      'properties': <String, Object?>{
                        'path': <String, Object?>{
                          'type': 'string',
                          'pattern': '^/',
                        },
                      },
                      'required': <Object?>[
                        'path',
                      ],
                      'additionalProperties': false,
                    },
                  ],
                  'description': 'Short chip text in output language.',
                },
                'query': <String, Object?>{
                  'oneOf': <Object?>[
                    <String, Object?>{
                      'type': 'string',
                    },
                    <String, Object?>{
                      'type': 'object',
                      'properties': <String, Object?>{
                        'path': <String, Object?>{
                          'type': 'string',
                          'pattern': '^/',
                        },
                      },
                      'required': <Object?>[
                        'path',
                      ],
                      'additionalProperties': false,
                    },
                  ],
                  'description': 'Full query to run when tapped.',
                },
              },
              'additionalProperties': false,
              'required': <Object?>[
                'label',
                'query',
              ],
            },
            'minItems': 2,
            'maxItems': 4,
          },
          <String, Object?>{
            'type': 'object',
            'properties': <String, Object?>{
              'path': <String, Object?>{
                'type': 'string',
                'pattern': '^/',
              },
            },
            'required': <Object?>[
              'path',
            ],
            'additionalProperties': false,
          },
        ],
      },
    },
    'required': <Object?>[
      'suggestions',
    ],
  },
  'ComparisonTable': <String, Object?>{
    'type': 'object',
    'description': 'N-way comparison (e.g. mutual funds vs FD). Use this instead of KeyValueGrid whenever comparing 2+ options across criteria.',
    'properties': <String, Object?>{
      'title': <String, Object?>{
        'oneOf': <Object?>[
          <String, Object?>{
            'type': 'string',
          },
          <String, Object?>{
            'type': 'object',
            'properties': <String, Object?>{
              'path': <String, Object?>{
                'type': 'string',
                'pattern': '^/',
              },
            },
            'required': <Object?>[
              'path',
            ],
            'additionalProperties': false,
          },
        ],
      },
      'columns': <String, Object?>{
        'oneOf': <Object?>[
          <String, Object?>{
            'type': 'array',
            'items': <String, Object?>{
              'type': 'object',
              'properties': <String, Object?>{
                'key': <String, Object?>{
                  'type': 'string',
                },
                'label': <String, Object?>{
                  'oneOf': <Object?>[
                    <String, Object?>{
                      'type': 'string',
                    },
                    <String, Object?>{
                      'type': 'object',
                      'properties': <String, Object?>{
                        'path': <String, Object?>{
                          'type': 'string',
                          'pattern': '^/',
                        },
                      },
                      'required': <Object?>[
                        'path',
                      ],
                      'additionalProperties': false,
                    },
                  ],
                },
              },
              'additionalProperties': false,
              'required': <Object?>[
                'key',
                'label',
              ],
            },
            'minItems': 2,
            'maxItems': 4,
          },
          <String, Object?>{
            'type': 'object',
            'properties': <String, Object?>{
              'path': <String, Object?>{
                'type': 'string',
                'pattern': '^/',
              },
            },
            'required': <Object?>[
              'path',
            ],
            'additionalProperties': false,
          },
        ],
      },
      'rows': <String, Object?>{
        'oneOf': <Object?>[
          <String, Object?>{
            'type': 'array',
            'items': <String, Object?>{
              'type': 'object',
              'properties': <String, Object?>{
                'label': <String, Object?>{
                  'oneOf': <Object?>[
                    <String, Object?>{
                      'type': 'string',
                    },
                    <String, Object?>{
                      'type': 'object',
                      'properties': <String, Object?>{
                        'path': <String, Object?>{
                          'type': 'string',
                          'pattern': '^/',
                        },
                      },
                      'required': <Object?>[
                        'path',
                      ],
                      'additionalProperties': false,
                    },
                  ],
                  'description': 'Criterion name (e.g. "Risk").',
                },
                'cells': <String, Object?>{
                  'oneOf': <Object?>[
                    <String, Object?>{
                      'type': 'array',
                      'items': <String, Object?>{
                        'oneOf': <Object?>[
                          <String, Object?>{
                            'type': 'string',
                          },
                          <String, Object?>{
                            'type': 'object',
                            'properties': <String, Object?>{
                              'path': <String, Object?>{
                                'type': 'string',
                                'pattern': '^/',
                              },
                            },
                            'required': <Object?>[
                              'path',
                            ],
                            'additionalProperties': false,
                          },
                        ],
                      },
                      'description': 'One cell per column',
                    },
                    <String, Object?>{
                      'type': 'object',
                      'properties': <String, Object?>{
                        'path': <String, Object?>{
                          'type': 'string',
                          'pattern': '^/',
                        },
                      },
                      'required': <Object?>[
                        'path',
                      ],
                      'additionalProperties': false,
                    },
                  ],
                },
              },
              'additionalProperties': false,
              'required': <Object?>[
                'label',
                'cells',
              ],
            },
            'minItems': 1,
            'maxItems': 10,
          },
          <String, Object?>{
            'type': 'object',
            'properties': <String, Object?>{
              'path': <String, Object?>{
                'type': 'string',
                'pattern': '^/',
              },
            },
            'required': <Object?>[
              'path',
            ],
            'additionalProperties': false,
          },
        ],
      },
      'highlightColumnKey': <String, Object?>{
        'type': 'string',
        'description': 'Key of the recommended column',
      },
      'footnote': <String, Object?>{
        'oneOf': <Object?>[
          <String, Object?>{
            'type': 'string',
          },
          <String, Object?>{
            'type': 'object',
            'properties': <String, Object?>{
              'path': <String, Object?>{
                'type': 'string',
                'pattern': '^/',
              },
            },
            'required': <Object?>[
              'path',
            ],
            'additionalProperties': false,
          },
        ],
      },
    },
    'required': <Object?>[
      'columns',
      'rows',
    ],
  },
  'Checklist': <String, Object?>{
    'type': 'object',
    'description': 'Diagnostic / to-do / packing list with optional check-off. Use for step-by-step remedies and preparation lists.',
    'properties': <String, Object?>{
      'title': <String, Object?>{
        'oneOf': <Object?>[
          <String, Object?>{
            'type': 'string',
          },
          <String, Object?>{
            'type': 'object',
            'properties': <String, Object?>{
              'path': <String, Object?>{
                'type': 'string',
                'pattern': '^/',
              },
            },
            'required': <Object?>[
              'path',
            ],
            'additionalProperties': false,
          },
        ],
      },
      'items': <String, Object?>{
        'oneOf': <Object?>[
          <String, Object?>{
            'type': 'array',
            'items': <String, Object?>{
              'type': 'object',
              'properties': <String, Object?>{
                'id': <String, Object?>{
                  'type': 'string',
                },
                'text': <String, Object?>{
                  'oneOf': <Object?>[
                    <String, Object?>{
                      'type': 'string',
                    },
                    <String, Object?>{
                      'type': 'object',
                      'properties': <String, Object?>{
                        'path': <String, Object?>{
                          'type': 'string',
                          'pattern': '^/',
                        },
                      },
                      'required': <Object?>[
                        'path',
                      ],
                      'additionalProperties': false,
                    },
                  ],
                },
                'detail': <String, Object?>{
                  'oneOf': <Object?>[
                    <String, Object?>{
                      'type': 'string',
                    },
                    <String, Object?>{
                      'type': 'object',
                      'properties': <String, Object?>{
                        'path': <String, Object?>{
                          'type': 'string',
                          'pattern': '^/',
                        },
                      },
                      'required': <Object?>[
                        'path',
                      ],
                      'additionalProperties': false,
                    },
                  ],
                },
                'checked': <String, Object?>{
                  'oneOf': <Object?>[
                    <String, Object?>{
                      'type': 'boolean',
                      'default': false,
                    },
                    <String, Object?>{
                      'type': 'object',
                      'properties': <String, Object?>{
                        'path': <String, Object?>{
                          'type': 'string',
                          'pattern': '^/',
                        },
                      },
                      'required': <Object?>[
                        'path',
                      ],
                      'additionalProperties': false,
                    },
                  ],
                },
              },
              'additionalProperties': false,
              'required': <Object?>[
                'id',
                'text',
              ],
            },
            'minItems': 1,
            'maxItems': 24,
          },
          <String, Object?>{
            'type': 'object',
            'properties': <String, Object?>{
              'path': <String, Object?>{
                'type': 'string',
                'pattern': '^/',
              },
            },
            'required': <Object?>[
              'path',
            ],
            'additionalProperties': false,
          },
        ],
      },
      'interactive': <String, Object?>{
        'oneOf': <Object?>[
          <String, Object?>{
            'type': 'boolean',
            'default': false,
          },
          <String, Object?>{
            'type': 'object',
            'properties': <String, Object?>{
              'path': <String, Object?>{
                'type': 'string',
                'pattern': '^/',
              },
            },
            'required': <Object?>[
              'path',
            ],
            'additionalProperties': false,
          },
        ],
        'description': 'Whether the user can toggle items.',
      },
    },
    'required': <Object?>[
      'items',
    ],
  },
  'SourceChips': <String, Object?>{
    'type': 'object',
    'description': 'Attribution chips for web sources that informed the answer. The SERVER appends this from search-grounding metadata — the model must never fabricate one.',
    'properties': <String, Object?>{
      'sources': <String, Object?>{
        'oneOf': <Object?>[
          <String, Object?>{
            'type': 'array',
            'items': <String, Object?>{
              'type': 'object',
              'properties': <String, Object?>{
                'title': <String, Object?>{
                  'oneOf': <Object?>[
                    <String, Object?>{
                      'type': 'string',
                    },
                    <String, Object?>{
                      'type': 'object',
                      'properties': <String, Object?>{
                        'path': <String, Object?>{
                          'type': 'string',
                          'pattern': '^/',
                        },
                      },
                      'required': <Object?>[
                        'path',
                      ],
                      'additionalProperties': false,
                    },
                  ],
                },
                'domain': <String, Object?>{
                  'oneOf': <Object?>[
                    <String, Object?>{
                      'type': 'string',
                    },
                    <String, Object?>{
                      'type': 'object',
                      'properties': <String, Object?>{
                        'path': <String, Object?>{
                          'type': 'string',
                          'pattern': '^/',
                        },
                      },
                      'required': <Object?>[
                        'path',
                      ],
                      'additionalProperties': false,
                    },
                  ],
                },
                'url': <String, Object?>{
                  'oneOf': <Object?>[
                    <String, Object?>{
                      'type': 'string',
                    },
                    <String, Object?>{
                      'type': 'object',
                      'properties': <String, Object?>{
                        'path': <String, Object?>{
                          'type': 'string',
                          'pattern': '^/',
                        },
                      },
                      'required': <Object?>[
                        'path',
                      ],
                      'additionalProperties': false,
                    },
                  ],
                },
              },
              'additionalProperties': false,
              'required': <Object?>[
                'title',
                'domain',
                'url',
              ],
            },
            'minItems': 1,
            'maxItems': 5,
          },
          <String, Object?>{
            'type': 'object',
            'properties': <String, Object?>{
              'path': <String, Object?>{
                'type': 'string',
                'pattern': '^/',
              },
            },
            'required': <Object?>[
              'path',
            ],
            'additionalProperties': false,
          },
        ],
      },
    },
    'required': <Object?>[
      'sources',
    ],
  },
  'CricketLiveScore': <String, Object?>{
    'type': 'object',
    'description': 'Live match card. Data arrives via the surface data model (adapter-fed, auto-refreshing); props are normally {path} bindings. Requires a legal Notice on the surface disclosing lagSeconds.',
    'properties': <String, Object?>{
      'matchId': <String, Object?>{
        'type': 'string',
      },
      'matchTitle': <String, Object?>{
        'oneOf': <Object?>[
          <String, Object?>{
            'type': 'string',
          },
          <String, Object?>{
            'type': 'object',
            'properties': <String, Object?>{
              'path': <String, Object?>{
                'type': 'string',
                'pattern': '^/',
              },
            },
            'required': <Object?>[
              'path',
            ],
            'additionalProperties': false,
          },
        ],
        'description': 'e.g. "IND vs AUS · 3rd T20I"',
      },
      'statusText': <String, Object?>{
        'oneOf': <Object?>[
          <String, Object?>{
            'type': 'string',
          },
          <String, Object?>{
            'type': 'object',
            'properties': <String, Object?>{
              'path': <String, Object?>{
                'type': 'string',
                'pattern': '^/',
              },
            },
            'required': <Object?>[
              'path',
            ],
            'additionalProperties': false,
          },
        ],
        'description': 'Localized state line',
      },
      'teams': <String, Object?>{
        'oneOf': <Object?>[
          <String, Object?>{
            'type': 'array',
            'items': <String, Object?>{
              'type': 'object',
              'properties': <String, Object?>{
                'name': <String, Object?>{
                  'oneOf': <Object?>[
                    <String, Object?>{
                      'type': 'string',
                    },
                    <String, Object?>{
                      'type': 'object',
                      'properties': <String, Object?>{
                        'path': <String, Object?>{
                          'type': 'string',
                          'pattern': '^/',
                        },
                      },
                      'required': <Object?>[
                        'path',
                      ],
                      'additionalProperties': false,
                    },
                  ],
                },
                'shortName': <String, Object?>{
                  'oneOf': <Object?>[
                    <String, Object?>{
                      'type': 'string',
                    },
                    <String, Object?>{
                      'type': 'object',
                      'properties': <String, Object?>{
                        'path': <String, Object?>{
                          'type': 'string',
                          'pattern': '^/',
                        },
                      },
                      'required': <Object?>[
                        'path',
                      ],
                      'additionalProperties': false,
                    },
                  ],
                },
                'logoUrl': <String, Object?>{
                  'oneOf': <Object?>[
                    <String, Object?>{
                      'type': 'string',
                    },
                    <String, Object?>{
                      'type': 'object',
                      'properties': <String, Object?>{
                        'path': <String, Object?>{
                          'type': 'string',
                          'pattern': '^/',
                        },
                      },
                      'required': <Object?>[
                        'path',
                      ],
                      'additionalProperties': false,
                    },
                  ],
                },
                'scoreText': <String, Object?>{
                  'oneOf': <Object?>[
                    <String, Object?>{
                      'type': 'string',
                    },
                    <String, Object?>{
                      'type': 'object',
                      'properties': <String, Object?>{
                        'path': <String, Object?>{
                          'type': 'string',
                          'pattern': '^/',
                        },
                      },
                      'required': <Object?>[
                        'path',
                      ],
                      'additionalProperties': false,
                    },
                  ],
                  'description': 'e.g. "186/4"',
                },
                'oversText': <String, Object?>{
                  'oneOf': <Object?>[
                    <String, Object?>{
                      'type': 'string',
                    },
                    <String, Object?>{
                      'type': 'object',
                      'properties': <String, Object?>{
                        'path': <String, Object?>{
                          'type': 'string',
                          'pattern': '^/',
                        },
                      },
                      'required': <Object?>[
                        'path',
                      ],
                      'additionalProperties': false,
                    },
                  ],
                  'description': 'e.g. "17.2"',
                },
              },
              'additionalProperties': false,
              'required': <Object?>[
                'name',
                'shortName',
              ],
            },
            'minItems': 2,
            'maxItems': 2,
          },
          <String, Object?>{
            'type': 'object',
            'properties': <String, Object?>{
              'path': <String, Object?>{
                'type': 'string',
                'pattern': '^/',
              },
            },
            'required': <Object?>[
              'path',
            ],
            'additionalProperties': false,
          },
        ],
      },
      'batters': <String, Object?>{
        'oneOf': <Object?>[
          <String, Object?>{
            'type': 'array',
            'items': <String, Object?>{
              'type': 'object',
              'properties': <String, Object?>{
                'name': <String, Object?>{
                  'oneOf': <Object?>[
                    <String, Object?>{
                      'type': 'string',
                    },
                    <String, Object?>{
                      'type': 'object',
                      'properties': <String, Object?>{
                        'path': <String, Object?>{
                          'type': 'string',
                          'pattern': '^/',
                        },
                      },
                      'required': <Object?>[
                        'path',
                      ],
                      'additionalProperties': false,
                    },
                  ],
                },
                'runsText': <String, Object?>{
                  'oneOf': <Object?>[
                    <String, Object?>{
                      'type': 'string',
                    },
                    <String, Object?>{
                      'type': 'object',
                      'properties': <String, Object?>{
                        'path': <String, Object?>{
                          'type': 'string',
                          'pattern': '^/',
                        },
                      },
                      'required': <Object?>[
                        'path',
                      ],
                      'additionalProperties': false,
                    },
                  ],
                  'description': 'e.g. "52*"',
                },
                'ballsText': <String, Object?>{
                  'oneOf': <Object?>[
                    <String, Object?>{
                      'type': 'string',
                    },
                    <String, Object?>{
                      'type': 'object',
                      'properties': <String, Object?>{
                        'path': <String, Object?>{
                          'type': 'string',
                          'pattern': '^/',
                        },
                      },
                      'required': <Object?>[
                        'path',
                      ],
                      'additionalProperties': false,
                    },
                  ],
                },
                'onStrike': <String, Object?>{
                  'oneOf': <Object?>[
                    <String, Object?>{
                      'type': 'boolean',
                      'default': false,
                    },
                    <String, Object?>{
                      'type': 'object',
                      'properties': <String, Object?>{
                        'path': <String, Object?>{
                          'type': 'string',
                          'pattern': '^/',
                        },
                      },
                      'required': <Object?>[
                        'path',
                      ],
                      'additionalProperties': false,
                    },
                  ],
                },
              },
              'additionalProperties': false,
              'required': <Object?>[
                'name',
                'runsText',
              ],
            },
            'maxItems': 2,
          },
          <String, Object?>{
            'type': 'object',
            'properties': <String, Object?>{
              'path': <String, Object?>{
                'type': 'string',
                'pattern': '^/',
              },
            },
            'required': <Object?>[
              'path',
            ],
            'additionalProperties': false,
          },
        ],
      },
      'bowler': <String, Object?>{
        'oneOf': <Object?>[
          <String, Object?>{
            'type': 'object',
            'properties': <String, Object?>{
              'name': <String, Object?>{
                'oneOf': <Object?>[
                  <String, Object?>{
                    'type': 'string',
                  },
                  <String, Object?>{
                    'type': 'object',
                    'properties': <String, Object?>{
                      'path': <String, Object?>{
                        'type': 'string',
                        'pattern': '^/',
                      },
                    },
                    'required': <Object?>[
                      'path',
                    ],
                    'additionalProperties': false,
                  },
                ],
              },
              'figuresText': <String, Object?>{
                'oneOf': <Object?>[
                  <String, Object?>{
                    'type': 'string',
                  },
                  <String, Object?>{
                    'type': 'object',
                    'properties': <String, Object?>{
                      'path': <String, Object?>{
                        'type': 'string',
                        'pattern': '^/',
                      },
                    },
                    'required': <Object?>[
                      'path',
                    ],
                    'additionalProperties': false,
                  },
                ],
                'description': 'e.g. "2/34"',
              },
              'oversText': <String, Object?>{
                'oneOf': <Object?>[
                  <String, Object?>{
                    'type': 'string',
                  },
                  <String, Object?>{
                    'type': 'object',
                    'properties': <String, Object?>{
                      'path': <String, Object?>{
                        'type': 'string',
                        'pattern': '^/',
                      },
                    },
                    'required': <Object?>[
                      'path',
                    ],
                    'additionalProperties': false,
                  },
                ],
              },
            },
            'additionalProperties': false,
            'required': <Object?>[
              'name',
            ],
          },
          <String, Object?>{
            'type': 'object',
            'properties': <String, Object?>{
              'path': <String, Object?>{
                'type': 'string',
                'pattern': '^/',
              },
            },
            'required': <Object?>[
              'path',
            ],
            'additionalProperties': false,
          },
        ],
      },
      'recentBalls': <String, Object?>{
        'oneOf': <Object?>[
          <String, Object?>{
            'type': 'array',
            'items': <String, Object?>{
              'oneOf': <Object?>[
                <String, Object?>{
                  'type': 'string',
                },
                <String, Object?>{
                  'type': 'object',
                  'properties': <String, Object?>{
                    'path': <String, Object?>{
                      'type': 'string',
                      'pattern': '^/',
                    },
                  },
                  'required': <Object?>[
                    'path',
                  ],
                  'additionalProperties': false,
                },
              ],
            },
            'maxItems': 6,
          },
          <String, Object?>{
            'type': 'object',
            'properties': <String, Object?>{
              'path': <String, Object?>{
                'type': 'string',
                'pattern': '^/',
              },
            },
            'required': <Object?>[
              'path',
            ],
            'additionalProperties': false,
          },
        ],
      },
      'lagSeconds': <String, Object?>{
        'oneOf': <Object?>[
          <String, Object?>{
            'type': 'number',
          },
          <String, Object?>{
            'type': 'object',
            'properties': <String, Object?>{
              'path': <String, Object?>{
                'type': 'string',
                'pattern': '^/',
              },
            },
            'required': <Object?>[
              'path',
            ],
            'additionalProperties': false,
          },
        ],
        'description': 'Configured display lag; drives the legal Notice.',
      },
      'updatedAtText': <String, Object?>{
        'oneOf': <Object?>[
          <String, Object?>{
            'type': 'string',
          },
          <String, Object?>{
            'type': 'object',
            'properties': <String, Object?>{
              'path': <String, Object?>{
                'type': 'string',
                'pattern': '^/',
              },
            },
            'required': <Object?>[
              'path',
            ],
            'additionalProperties': false,
          },
        ],
      },
    },
    'required': <Object?>[
      'matchId',
      'matchTitle',
      'statusText',
      'teams',
      'lagSeconds',
      'updatedAtText',
    ],
  },
  'PanchangCard': <String, Object?>{
    'type': 'object',
    'description': 'Daily panchang for a location. All times pre-formatted and localized by the adapter (cacheable per city+date).',
    'properties': <String, Object?>{
      'dateText': <String, Object?>{
        'oneOf': <Object?>[
          <String, Object?>{
            'type': 'string',
          },
          <String, Object?>{
            'type': 'object',
            'properties': <String, Object?>{
              'path': <String, Object?>{
                'type': 'string',
                'pattern': '^/',
              },
            },
            'required': <Object?>[
              'path',
            ],
            'additionalProperties': false,
          },
        ],
        'description': 'Localized date incl. lunar calendar.',
      },
      'locationName': <String, Object?>{
        'oneOf': <Object?>[
          <String, Object?>{
            'type': 'string',
          },
          <String, Object?>{
            'type': 'object',
            'properties': <String, Object?>{
              'path': <String, Object?>{
                'type': 'string',
                'pattern': '^/',
              },
            },
            'required': <Object?>[
              'path',
            ],
            'additionalProperties': false,
          },
        ],
      },
      'tithi': <String, Object?>{
        'oneOf': <Object?>[
          <String, Object?>{
            'type': 'object',
            'properties': <String, Object?>{
              'name': <String, Object?>{
                'oneOf': <Object?>[
                  <String, Object?>{
                    'type': 'string',
                  },
                  <String, Object?>{
                    'type': 'object',
                    'properties': <String, Object?>{
                      'path': <String, Object?>{
                        'type': 'string',
                        'pattern': '^/',
                      },
                    },
                    'required': <Object?>[
                      'path',
                    ],
                    'additionalProperties': false,
                  },
                ],
              },
              'endsAtText': <String, Object?>{
                'oneOf': <Object?>[
                  <String, Object?>{
                    'type': 'string',
                  },
                  <String, Object?>{
                    'type': 'object',
                    'properties': <String, Object?>{
                      'path': <String, Object?>{
                        'type': 'string',
                        'pattern': '^/',
                      },
                    },
                    'required': <Object?>[
                      'path',
                    ],
                    'additionalProperties': false,
                  },
                ],
              },
            },
            'additionalProperties': false,
            'required': <Object?>[
              'name',
            ],
          },
          <String, Object?>{
            'type': 'object',
            'properties': <String, Object?>{
              'path': <String, Object?>{
                'type': 'string',
                'pattern': '^/',
              },
            },
            'required': <Object?>[
              'path',
            ],
            'additionalProperties': false,
          },
        ],
      },
      'nakshatra': <String, Object?>{
        'oneOf': <Object?>[
          <String, Object?>{
            'type': 'object',
            'properties': <String, Object?>{
              'name': <String, Object?>{
                'oneOf': <Object?>[
                  <String, Object?>{
                    'type': 'string',
                  },
                  <String, Object?>{
                    'type': 'object',
                    'properties': <String, Object?>{
                      'path': <String, Object?>{
                        'type': 'string',
                        'pattern': '^/',
                      },
                    },
                    'required': <Object?>[
                      'path',
                    ],
                    'additionalProperties': false,
                  },
                ],
              },
              'endsAtText': <String, Object?>{
                'oneOf': <Object?>[
                  <String, Object?>{
                    'type': 'string',
                  },
                  <String, Object?>{
                    'type': 'object',
                    'properties': <String, Object?>{
                      'path': <String, Object?>{
                        'type': 'string',
                        'pattern': '^/',
                      },
                    },
                    'required': <Object?>[
                      'path',
                    ],
                    'additionalProperties': false,
                  },
                ],
              },
            },
            'additionalProperties': false,
            'required': <Object?>[
              'name',
            ],
          },
          <String, Object?>{
            'type': 'object',
            'properties': <String, Object?>{
              'path': <String, Object?>{
                'type': 'string',
                'pattern': '^/',
              },
            },
            'required': <Object?>[
              'path',
            ],
            'additionalProperties': false,
          },
        ],
      },
      'yoga': <String, Object?>{
        'oneOf': <Object?>[
          <String, Object?>{
            'type': 'object',
            'properties': <String, Object?>{
              'name': <String, Object?>{
                'oneOf': <Object?>[
                  <String, Object?>{
                    'type': 'string',
                  },
                  <String, Object?>{
                    'type': 'object',
                    'properties': <String, Object?>{
                      'path': <String, Object?>{
                        'type': 'string',
                        'pattern': '^/',
                      },
                    },
                    'required': <Object?>[
                      'path',
                    ],
                    'additionalProperties': false,
                  },
                ],
              },
              'endsAtText': <String, Object?>{
                'oneOf': <Object?>[
                  <String, Object?>{
                    'type': 'string',
                  },
                  <String, Object?>{
                    'type': 'object',
                    'properties': <String, Object?>{
                      'path': <String, Object?>{
                        'type': 'string',
                        'pattern': '^/',
                      },
                    },
                    'required': <Object?>[
                      'path',
                    ],
                    'additionalProperties': false,
                  },
                ],
              },
            },
            'additionalProperties': false,
            'required': <Object?>[
              'name',
            ],
          },
          <String, Object?>{
            'type': 'object',
            'properties': <String, Object?>{
              'path': <String, Object?>{
                'type': 'string',
                'pattern': '^/',
              },
            },
            'required': <Object?>[
              'path',
            ],
            'additionalProperties': false,
          },
        ],
      },
      'karana': <String, Object?>{
        'oneOf': <Object?>[
          <String, Object?>{
            'type': 'object',
            'properties': <String, Object?>{
              'name': <String, Object?>{
                'oneOf': <Object?>[
                  <String, Object?>{
                    'type': 'string',
                  },
                  <String, Object?>{
                    'type': 'object',
                    'properties': <String, Object?>{
                      'path': <String, Object?>{
                        'type': 'string',
                        'pattern': '^/',
                      },
                    },
                    'required': <Object?>[
                      'path',
                    ],
                    'additionalProperties': false,
                  },
                ],
              },
              'endsAtText': <String, Object?>{
                'oneOf': <Object?>[
                  <String, Object?>{
                    'type': 'string',
                  },
                  <String, Object?>{
                    'type': 'object',
                    'properties': <String, Object?>{
                      'path': <String, Object?>{
                        'type': 'string',
                        'pattern': '^/',
                      },
                    },
                    'required': <Object?>[
                      'path',
                    ],
                    'additionalProperties': false,
                  },
                ],
              },
            },
            'additionalProperties': false,
            'required': <Object?>[
              'name',
            ],
          },
          <String, Object?>{
            'type': 'object',
            'properties': <String, Object?>{
              'path': <String, Object?>{
                'type': 'string',
                'pattern': '^/',
              },
            },
            'required': <Object?>[
              'path',
            ],
            'additionalProperties': false,
          },
        ],
      },
      'sunriseText': <String, Object?>{
        'oneOf': <Object?>[
          <String, Object?>{
            'type': 'string',
          },
          <String, Object?>{
            'type': 'object',
            'properties': <String, Object?>{
              'path': <String, Object?>{
                'type': 'string',
                'pattern': '^/',
              },
            },
            'required': <Object?>[
              'path',
            ],
            'additionalProperties': false,
          },
        ],
      },
      'sunsetText': <String, Object?>{
        'oneOf': <Object?>[
          <String, Object?>{
            'type': 'string',
          },
          <String, Object?>{
            'type': 'object',
            'properties': <String, Object?>{
              'path': <String, Object?>{
                'type': 'string',
                'pattern': '^/',
              },
            },
            'required': <Object?>[
              'path',
            ],
            'additionalProperties': false,
          },
        ],
      },
      'rahuKalam': <String, Object?>{
        'oneOf': <Object?>[
          <String, Object?>{
            'type': 'object',
            'properties': <String, Object?>{
              'startText': <String, Object?>{
                'oneOf': <Object?>[
                  <String, Object?>{
                    'type': 'string',
                  },
                  <String, Object?>{
                    'type': 'object',
                    'properties': <String, Object?>{
                      'path': <String, Object?>{
                        'type': 'string',
                        'pattern': '^/',
                      },
                    },
                    'required': <Object?>[
                      'path',
                    ],
                    'additionalProperties': false,
                  },
                ],
              },
              'endText': <String, Object?>{
                'oneOf': <Object?>[
                  <String, Object?>{
                    'type': 'string',
                  },
                  <String, Object?>{
                    'type': 'object',
                    'properties': <String, Object?>{
                      'path': <String, Object?>{
                        'type': 'string',
                        'pattern': '^/',
                      },
                    },
                    'required': <Object?>[
                      'path',
                    ],
                    'additionalProperties': false,
                  },
                ],
              },
            },
            'additionalProperties': false,
            'required': <Object?>[
              'startText',
              'endText',
            ],
          },
          <String, Object?>{
            'type': 'object',
            'properties': <String, Object?>{
              'path': <String, Object?>{
                'type': 'string',
                'pattern': '^/',
              },
            },
            'required': <Object?>[
              'path',
            ],
            'additionalProperties': false,
          },
        ],
      },
      'festivals': <String, Object?>{
        'oneOf': <Object?>[
          <String, Object?>{
            'type': 'array',
            'items': <String, Object?>{
              'oneOf': <Object?>[
                <String, Object?>{
                  'type': 'string',
                },
                <String, Object?>{
                  'type': 'object',
                  'properties': <String, Object?>{
                    'path': <String, Object?>{
                      'type': 'string',
                      'pattern': '^/',
                    },
                  },
                  'required': <Object?>[
                    'path',
                  ],
                  'additionalProperties': false,
                },
              ],
            },
            'maxItems': 3,
          },
          <String, Object?>{
            'type': 'object',
            'properties': <String, Object?>{
              'path': <String, Object?>{
                'type': 'string',
                'pattern': '^/',
              },
            },
            'required': <Object?>[
              'path',
            ],
            'additionalProperties': false,
          },
        ],
      },
      'variant': <String, Object?>{
        'oneOf': <Object?>[
          <String, Object?>{
            'type': 'string',
            'enum': <Object?>[
              'compact',
              'full',
            ],
            'default': 'full',
          },
          <String, Object?>{
            'type': 'object',
            'properties': <String, Object?>{
              'path': <String, Object?>{
                'type': 'string',
                'pattern': '^/',
              },
            },
            'required': <Object?>[
              'path',
            ],
            'additionalProperties': false,
          },
        ],
      },
    },
    'required': <Object?>[
      'dateText',
      'locationName',
      'tithi',
      'nakshatra',
      'sunriseText',
      'sunsetText',
      'rahuKalam',
    ],
  },
  'WeatherStrip': <String, Object?>{
    'type': 'object',
    'description': 'Current conditions + multi-day forecast for one location.',
    'properties': <String, Object?>{
      'locationName': <String, Object?>{
        'oneOf': <Object?>[
          <String, Object?>{
            'type': 'string',
          },
          <String, Object?>{
            'type': 'object',
            'properties': <String, Object?>{
              'path': <String, Object?>{
                'type': 'string',
                'pattern': '^/',
              },
            },
            'required': <Object?>[
              'path',
            ],
            'additionalProperties': false,
          },
        ],
      },
      'current': <String, Object?>{
        'oneOf': <Object?>[
          <String, Object?>{
            'type': 'object',
            'properties': <String, Object?>{
              'tempText': <String, Object?>{
                'oneOf': <Object?>[
                  <String, Object?>{
                    'type': 'string',
                  },
                  <String, Object?>{
                    'type': 'object',
                    'properties': <String, Object?>{
                      'path': <String, Object?>{
                        'type': 'string',
                        'pattern': '^/',
                      },
                    },
                    'required': <Object?>[
                      'path',
                    ],
                    'additionalProperties': false,
                  },
                ],
              },
              'condition': <String, Object?>{
                'oneOf': <Object?>[
                  <String, Object?>{
                    'type': 'string',
                    'enum': <Object?>[
                      'clear',
                      'partlyCloudy',
                      'cloudy',
                      'mist',
                      'haze',
                      'rain',
                      'heavyRain',
                      'thunderstorm',
                      'snow',
                    ],
                  },
                  <String, Object?>{
                    'type': 'object',
                    'properties': <String, Object?>{
                      'path': <String, Object?>{
                        'type': 'string',
                        'pattern': '^/',
                      },
                    },
                    'required': <Object?>[
                      'path',
                    ],
                    'additionalProperties': false,
                  },
                ],
              },
              'conditionText': <String, Object?>{
                'oneOf': <Object?>[
                  <String, Object?>{
                    'type': 'string',
                  },
                  <String, Object?>{
                    'type': 'object',
                    'properties': <String, Object?>{
                      'path': <String, Object?>{
                        'type': 'string',
                        'pattern': '^/',
                      },
                    },
                    'required': <Object?>[
                      'path',
                    ],
                    'additionalProperties': false,
                  },
                ],
                'description': 'Localized condition line.',
              },
              'feelsLikeText': <String, Object?>{
                'oneOf': <Object?>[
                  <String, Object?>{
                    'type': 'string',
                  },
                  <String, Object?>{
                    'type': 'object',
                    'properties': <String, Object?>{
                      'path': <String, Object?>{
                        'type': 'string',
                        'pattern': '^/',
                      },
                    },
                    'required': <Object?>[
                      'path',
                    ],
                    'additionalProperties': false,
                  },
                ],
              },
              'humidityText': <String, Object?>{
                'oneOf': <Object?>[
                  <String, Object?>{
                    'type': 'string',
                  },
                  <String, Object?>{
                    'type': 'object',
                    'properties': <String, Object?>{
                      'path': <String, Object?>{
                        'type': 'string',
                        'pattern': '^/',
                      },
                    },
                    'required': <Object?>[
                      'path',
                    ],
                    'additionalProperties': false,
                  },
                ],
              },
              'windText': <String, Object?>{
                'oneOf': <Object?>[
                  <String, Object?>{
                    'type': 'string',
                  },
                  <String, Object?>{
                    'type': 'object',
                    'properties': <String, Object?>{
                      'path': <String, Object?>{
                        'type': 'string',
                        'pattern': '^/',
                      },
                    },
                    'required': <Object?>[
                      'path',
                    ],
                    'additionalProperties': false,
                  },
                ],
              },
            },
            'additionalProperties': false,
            'required': <Object?>[
              'tempText',
              'condition',
              'conditionText',
            ],
          },
          <String, Object?>{
            'type': 'object',
            'properties': <String, Object?>{
              'path': <String, Object?>{
                'type': 'string',
                'pattern': '^/',
              },
            },
            'required': <Object?>[
              'path',
            ],
            'additionalProperties': false,
          },
        ],
      },
      'days': <String, Object?>{
        'oneOf': <Object?>[
          <String, Object?>{
            'type': 'array',
            'items': <String, Object?>{
              'type': 'object',
              'properties': <String, Object?>{
                'dayLabel': <String, Object?>{
                  'oneOf': <Object?>[
                    <String, Object?>{
                      'type': 'string',
                    },
                    <String, Object?>{
                      'type': 'object',
                      'properties': <String, Object?>{
                        'path': <String, Object?>{
                          'type': 'string',
                          'pattern': '^/',
                        },
                      },
                      'required': <Object?>[
                        'path',
                      ],
                      'additionalProperties': false,
                    },
                  ],
                },
                'minText': <String, Object?>{
                  'oneOf': <Object?>[
                    <String, Object?>{
                      'type': 'string',
                    },
                    <String, Object?>{
                      'type': 'object',
                      'properties': <String, Object?>{
                        'path': <String, Object?>{
                          'type': 'string',
                          'pattern': '^/',
                        },
                      },
                      'required': <Object?>[
                        'path',
                      ],
                      'additionalProperties': false,
                    },
                  ],
                },
                'maxText': <String, Object?>{
                  'oneOf': <Object?>[
                    <String, Object?>{
                      'type': 'string',
                    },
                    <String, Object?>{
                      'type': 'object',
                      'properties': <String, Object?>{
                        'path': <String, Object?>{
                          'type': 'string',
                          'pattern': '^/',
                        },
                      },
                      'required': <Object?>[
                        'path',
                      ],
                      'additionalProperties': false,
                    },
                  ],
                },
                'condition': <String, Object?>{
                  'oneOf': <Object?>[
                    <String, Object?>{
                      'type': 'string',
                      'enum': <Object?>[
                        'clear',
                        'partlyCloudy',
                        'cloudy',
                        'mist',
                        'haze',
                        'rain',
                        'heavyRain',
                        'thunderstorm',
                        'snow',
                      ],
                    },
                    <String, Object?>{
                      'type': 'object',
                      'properties': <String, Object?>{
                        'path': <String, Object?>{
                          'type': 'string',
                          'pattern': '^/',
                        },
                      },
                      'required': <Object?>[
                        'path',
                      ],
                      'additionalProperties': false,
                    },
                  ],
                },
                'rainPctText': <String, Object?>{
                  'oneOf': <Object?>[
                    <String, Object?>{
                      'type': 'string',
                    },
                    <String, Object?>{
                      'type': 'object',
                      'properties': <String, Object?>{
                        'path': <String, Object?>{
                          'type': 'string',
                          'pattern': '^/',
                        },
                      },
                      'required': <Object?>[
                        'path',
                      ],
                      'additionalProperties': false,
                    },
                  ],
                },
              },
              'additionalProperties': false,
              'required': <Object?>[
                'dayLabel',
                'minText',
                'maxText',
                'condition',
              ],
            },
            'minItems': 3,
            'maxItems': 7,
          },
          <String, Object?>{
            'type': 'object',
            'properties': <String, Object?>{
              'path': <String, Object?>{
                'type': 'string',
                'pattern': '^/',
              },
            },
            'required': <Object?>[
              'path',
            ],
            'additionalProperties': false,
          },
        ],
      },
      'alerts': <String, Object?>{
        'oneOf': <Object?>[
          <String, Object?>{
            'type': 'array',
            'items': <String, Object?>{
              'type': 'object',
              'properties': <String, Object?>{
                'severity': <String, Object?>{
                  'oneOf': <Object?>[
                    <String, Object?>{
                      'type': 'string',
                      'enum': <Object?>[
                        'watch',
                        'warning',
                      ],
                    },
                    <String, Object?>{
                      'type': 'object',
                      'properties': <String, Object?>{
                        'path': <String, Object?>{
                          'type': 'string',
                          'pattern': '^/',
                        },
                      },
                      'required': <Object?>[
                        'path',
                      ],
                      'additionalProperties': false,
                    },
                  ],
                },
                'text': <String, Object?>{
                  'oneOf': <Object?>[
                    <String, Object?>{
                      'type': 'string',
                    },
                    <String, Object?>{
                      'type': 'object',
                      'properties': <String, Object?>{
                        'path': <String, Object?>{
                          'type': 'string',
                          'pattern': '^/',
                        },
                      },
                      'required': <Object?>[
                        'path',
                      ],
                      'additionalProperties': false,
                    },
                  ],
                },
              },
              'additionalProperties': false,
              'required': <Object?>[
                'severity',
                'text',
              ],
            },
            'maxItems': 3,
          },
          <String, Object?>{
            'type': 'object',
            'properties': <String, Object?>{
              'path': <String, Object?>{
                'type': 'string',
                'pattern': '^/',
              },
            },
            'required': <Object?>[
              'path',
            ],
            'additionalProperties': false,
          },
        ],
      },
    },
    'required': <Object?>[
      'locationName',
      'current',
      'days',
    ],
  },
  'AqiMeter': <String, Object?>{
    'type': 'object',
    'description': 'AQI gauge (CPCB scale) with health advice.',
    'properties': <String, Object?>{
      'locationName': <String, Object?>{
        'oneOf': <Object?>[
          <String, Object?>{
            'type': 'string',
          },
          <String, Object?>{
            'type': 'object',
            'properties': <String, Object?>{
              'path': <String, Object?>{
                'type': 'string',
                'pattern': '^/',
              },
            },
            'required': <Object?>[
              'path',
            ],
            'additionalProperties': false,
          },
        ],
      },
      'aqi': <String, Object?>{
        'oneOf': <Object?>[
          <String, Object?>{
            'type': 'number',
          },
          <String, Object?>{
            'type': 'object',
            'properties': <String, Object?>{
              'path': <String, Object?>{
                'type': 'string',
                'pattern': '^/',
              },
            },
            'required': <Object?>[
              'path',
            ],
            'additionalProperties': false,
          },
        ],
      },
      'category': <String, Object?>{
        'oneOf': <Object?>[
          <String, Object?>{
            'type': 'string',
            'enum': <Object?>[
              'good',
              'satisfactory',
              'moderate',
              'poor',
              'veryPoor',
              'severe',
            ],
          },
          <String, Object?>{
            'type': 'object',
            'properties': <String, Object?>{
              'path': <String, Object?>{
                'type': 'string',
                'pattern': '^/',
              },
            },
            'required': <Object?>[
              'path',
            ],
            'additionalProperties': false,
          },
        ],
        'description': 'CPCB category; drives the color band.',
      },
      'categoryText': <String, Object?>{
        'oneOf': <Object?>[
          <String, Object?>{
            'type': 'string',
          },
          <String, Object?>{
            'type': 'object',
            'properties': <String, Object?>{
              'path': <String, Object?>{
                'type': 'string',
                'pattern': '^/',
              },
            },
            'required': <Object?>[
              'path',
            ],
            'additionalProperties': false,
          },
        ],
        'description': 'Localized category label.',
      },
      'dominantPollutant': <String, Object?>{
        'oneOf': <Object?>[
          <String, Object?>{
            'type': 'string',
          },
          <String, Object?>{
            'type': 'object',
            'properties': <String, Object?>{
              'path': <String, Object?>{
                'type': 'string',
                'pattern': '^/',
              },
            },
            'required': <Object?>[
              'path',
            ],
            'additionalProperties': false,
          },
        ],
      },
      'stationName': <String, Object?>{
        'oneOf': <Object?>[
          <String, Object?>{
            'type': 'string',
          },
          <String, Object?>{
            'type': 'object',
            'properties': <String, Object?>{
              'path': <String, Object?>{
                'type': 'string',
                'pattern': '^/',
              },
            },
            'required': <Object?>[
              'path',
            ],
            'additionalProperties': false,
          },
        ],
      },
      'updatedAtText': <String, Object?>{
        'oneOf': <Object?>[
          <String, Object?>{
            'type': 'string',
          },
          <String, Object?>{
            'type': 'object',
            'properties': <String, Object?>{
              'path': <String, Object?>{
                'type': 'string',
                'pattern': '^/',
              },
            },
            'required': <Object?>[
              'path',
            ],
            'additionalProperties': false,
          },
        ],
      },
      'healthAdviceText': <String, Object?>{
        'oneOf': <Object?>[
          <String, Object?>{
            'type': 'string',
          },
          <String, Object?>{
            'type': 'object',
            'properties': <String, Object?>{
              'path': <String, Object?>{
                'type': 'string',
                'pattern': '^/',
              },
            },
            'required': <Object?>[
              'path',
            ],
            'additionalProperties': false,
          },
        ],
      },
    },
    'required': <Object?>[
      'locationName',
      'aqi',
      'category',
      'categoryText',
      'updatedAtText',
      'healthAdviceText',
    ],
  },
};
